### ISSUE TITLE
Improve README layout

### ISSUE THREAD

**Issue by pedromxavier** [psrenergy/QUBO.jl#4]
The main idea is to replace the "`QUBO.jl` features" section with something like
![image](https://github.com/psrenergy/QUBO.jl/assets/31925649/f0825778-dbe1-4aa4-931b-c82b744e2d1d)
and remove those package's logos from the bottom and include PSR & Purdue logos (UFRJ? NASA?), eventually with a brief explanation on the partnership.

What do you think? @bernalde @pedroripper @joaquimg

**Comment by bernalde** [comment]
I like the new layout! The only thing I would certainly not include is a NASA logo. Just Purdue and USRA from my side. I think UFRJ as well, as you are doing your MSc while writing this, and Nelson Maculan is a coauthor of the paper.
